#pragma config(Sensor, in1,    autonSelector,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  elevator,       sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  chainBar,       sensorQuadEncoder)
#pragma config(Motor,  port1,           driveLeftOne,  tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLeftTwo,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeftThree, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeftFour, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveRightOne, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveRightTwo, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRightThree, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveRightFour, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define PID_INTEGRAL_LIMIT  50
#define PID_DRIVE_MAX       127
#define PID_DRIVE_MIN     (-127)
#define CYCLE_TIME 					20


static float pidRequestedValueLeft, pidRequestedValueRight;
static float Kp = 1;
static float Ki = 0;
static float Kd = 0;
static float leftDriveScale = 0.6; //Multiply faster motor by this so speed is equal with slower motor
static float rightDriveScale = 1;
static bool pidActive = true;


static float velErrorKp = .1;

bool matchSideVelocities = true;

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task pidController()
{
	//Initialize PID variables, only using P for now
	float  pidSensorCurrentValueLeft, pidSensorCurrentValueRight;
	float  pidErrorLeft, pidErrorRight;
	float  pidLastErrorLeft, pidLastErrorRight;
	float  pidIntegralLeft, pidIntegralRight;
	float  pidDerivativeLeft, pidDerivativeRight;
	float  pidDriveLeft, pidDriveRight;

	float velDiffError;


	//Clear sensor values
	SensorValue[rightEnc] = 0;
	SensorValue[leftEnc] = 0;

	pidLastErrorLeft = 0;
	pidLastErrorRight = 0;
	pidIntegralLeft = 0;
	pidIntegralRight = 0;

	velDiffError = 0;
	while(true)
	{
		//If the pid is set to active
		if(pidActive)
		{
			//Calculate proportional portion
			pidSensorCurrentValueLeft = SensorValue[leftEnc];
			pidSensorCurrentValueRight = SensorValue[rightEnc];

			pidErrorLeft = pidSensorCurrentValueLeft - pidRequestedValueLeft;
			pidErrorRight = pidSensorCurrentValueRight - pidRequestedValueRight;


			// Calculate integral portion
			// Add the error to the integral unless the error bound grows too large
			if(abs(pidErrorLeft) < PID_INTEGRAL_LIMIT)
				pidIntegralLeft = pidIntegralLeft + pidErrorLeft;
			else
				pidIntegralLeft = 0;

			if(abs(pidErrorRight) < PID_INTEGRAL_LIMIT)
				pidIntegralRight = pidIntegralRight + pidErrorRight;
			else
				pidIntegralRight = 0;

			//Calculate derivitave portion
			pidDerivativeLeft = pidErrorLeft - pidLastErrorLeft;
			pidDerivativeRight = pidErrorRight - pidLastErrorRight;

			pidLastErrorLeft  = pidErrorLeft;
			pidLastErrorRight = pidErrorRight;

			//Compensate for one side moving faster
			velDiffError = pidSensorCurrentValueLeft - pidSensorCurrentValueRight;

			writeDebugStreamLine("LeftEnc: %f", pidSensorCurrentValueLeft);
			writeDebugStreamLine("RightEnc: %f", pidSensorCurrentValueRight);


			//Calculate drive
			pidDriveLeft = (Kp * pidErrorLeft) + (Ki * pidIntegralLeft) + (Kd * pidDerivativeLeft);
			pidDriveRight = (Kp * pidErrorRight) + (Ki * pidIntegralRight) + (Kd * pidDerivativeRight);



			//Scale down to 127, -127 so drive distance gains do not override corrective vel matching
			if( pidDriveLeft > PID_DRIVE_MAX )
				pidDriveLeft = PID_DRIVE_MAX;
			if( pidDriveLeft < PID_DRIVE_MIN )
				pidDriveLeft = PID_DRIVE_MIN;

			if( pidDriveRight > PID_DRIVE_MAX )
				pidDriveRight = PID_DRIVE_MAX;
			if( pidDriveRight < PID_DRIVE_MIN )
				pidDriveRight = PID_DRIVE_MIN;

					writeDebugStreamLine("DriveBeforeCorrectLeft: %f", pidDriveLeft);
				writeDebugStreamLine("DriveBeforeCorrectRight: %f", pidDriveRight);


		  //Recalculate drive with corrective vel matching on each side
			pidDriveLeft = pidDriveLeft + (velErrorKp * velDiffError);
			pidDriveRight = pidDriveRight - (velErrorKp * velDiffError);

			writeDebugStreamLine("Vel Error: %f", velDiffError);

			writeDebugStreamLine("DriveLeft After: %f", pidDriveLeft);
			writeDebugStreamLine("DriveRight After: %f", pidDriveRight);


			//Prevent setting over valid motor values once more
			if( pidDriveLeft > PID_DRIVE_MAX )
				pidDriveLeft = PID_DRIVE_MAX;
			if( pidDriveLeft < PID_DRIVE_MIN )
				pidDriveLeft = PID_DRIVE_MIN;

			if( pidDriveRight > PID_DRIVE_MAX )
				pidDriveRight = PID_DRIVE_MAX;
			if( pidDriveRight < PID_DRIVE_MIN )
				pidDriveRight = PID_DRIVE_MIN;

			writeDebugStreamLine("Final Left : %f", pidDriveLeft);
			writeDebugStreamLine("Final Right : %f", pidDriveRight);


			//Drive using PID commands
			motor[driveLeftOne] = (int)((float)pidDriveLeft * (-1.0)*leftDriveScale);
			motor[driveLeftTwo] = (int)((float)pidDriveLeft * (-1.0)*leftDriveScale);
			motor[driveLeftThree] = (int)((float)pidDriveLeft * (-1.0)*leftDriveScale);
			motor[driveLeftFour] = (int)((float)pidDriveLeft * (-1.0)*leftDriveScale);
			motor[driveRightOne] = (int)((float)pidDriveRight * (-1.0)*rightDriveScale);
			motor[driveRightTwo] = (int)((float)pidDriveRight * (-1.0)*rightDriveScale);
			motor[driveRightThree] = (int)((float)pidDriveRight * (-1.0)*rightDriveScale);
			motor[driveRightFour] = (int)((float)pidDriveRight * (-1.0)*rightDriveScale);

			wait1Msec(CYCLE_TIME);
		}
		else //delete the emails, i mean variables
		{
			pidSensorCurrentValueLeft = 0;
			pidSensorCurrentValueRight = 0;
			pidErrorLeft = 0;
			pidErrorRight = 0;
			pidLastErrorLeft = 0;
			pidLastErrorRight = 0;
			pidIntegralLeft = 0;
			pidIntegralRight = 0;
			pidDerivativeLeft = 0;
			pidIntegralRight = 0;
			pidDriveLeft= 0;
			pidDriveRight = 0;
			motor[driveLeftOne] = 0;
			motor[driveLeftTwo] = 0;
			motor[driveLeftThree] = 0;
			motor[driveLeftFour] = 0;
			motor[driveRightOne] = 0;
			motor[driveRightTwo] = 0;
			motor[driveRightThree] = 0;
			motor[driveRightFour] = 0;
		}

	}
}




void drive(int anglesLeft, int anglesRight)
{
	matchSideVelocities = false;
	SensorValue[leftEnc] = 0;
	SensorValue[rightEnc] = 0;

	pidRequestedValueLeft = anglesLeft;
	pidRequestedValueRight = anglesRight;

}

void driveStraight(int dist)
{
	matchSideVelocities = true;
	SensorValue[leftEnc] = 0;
	SensorValue[rightEnc] = 0;

	pidRequestedValueLeft = dist;
	pidRequestedValueRight = dist;

}
void mogoDown()
{
	motor[liftLeft] = -127;
	motor[liftRight] = -127;
	wait1Msec(500);
	motor[liftLeft] = 0;
	motor[liftRight] = 0;
}

void mogoDownStrong()
{
	motor[liftLeft] = -127;
	motor[liftRight] = -127;
	wait1Msec(800);
	motor[liftLeft] = 0;
	motor[liftRight] = 0;
}

void mogoUp()
{
	motor[liftLeft] = 127;
	motor[liftRight] = 127;
	wait1Msec(800);
	motor[liftLeft] = 0;
	motor[liftRight] = 0;
}


task autonomous()
{
	/*
if(SensorValue[autonSelector] < 1700)
	{
		//Red
		startTask(pidController);
		drive(1620,1620);
		mogoDown();
		wait1Msec(1350);
		mogoUp();
		wait1Msec(700);
		drive(-800,-800);
		wait1Msec(1000);
		drive(625,-625);
		wait1Msec(1400);
		drive(1450,1050);
		wait1Msec(2200);
		drive(600,600);
		wait1Msec(1000);
		mogoDown();
		wait1Msec(1000);
		drive(-700,-700);
  }
  else
	{
		startTask(pidController);
		drive(1600,1600);
		mogoDown();
		wait1Msec(1350);
		mogoUp();
		wait1Msec(700);
		drive(-800,-800);
		wait1Msec(1000);
		drive(-625,625);
		wait1Msec(1400);
		drive(1050,1450);
		wait1Msec(2200);
		drive(600,600);
		wait1Msec(1000);
		mogoDownStrong();
		wait1Msec(1000);
		drive(-700,-700);
	}*/
		startTask(pidController);
	  driveStraight(8000);
		//drive(1000,1000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
#define PID_INTEGRAL_LIMIT_ELEVATOR  50

static float pidRequestedElevator;
static float elevatorKp = 1;
static float elevatorKi = 0;
static float elevatorKd = 0;
static bool pidLift = false;


task liftControl()
{
	float  currentElevatorPos;
	float  pidElevatorError;
	float  pidLastElevatorError;
	float  pidElevatorIntegral;
	float  pidElevatorDerivative;
	float  pidElevatorDrive;
	while(true)
	{
		if(pidLift)
		{
			currentElevatorPos = SensorValue[elevator];

			pidElevatorError = currentElevatorPos - pidRequestedElevator;

			// Calculate integral portion
			// Add the error to the integral unless the error bound grows too large
			if(abs(pidElevatorError) < PID_INTEGRAL_LIMIT_ELEVATOR)
				pidElevatorIntegral = pidElevatorIntegral + pidElevatorError;
			else
				pidElevatorIntegral = 0;


			//Calculate derivitave portion
			pidElevatorDerivative = pidElevatorError - pidLastElevatorError;

			pidLastElevatorError = pidElevatorError;


			//Calculate drive
			pidElevatorDrive = (elevatorKp * pidElevatorError) + (elevatorKi * pidElevatorIntegral) + (elevatorKd * pidElevatorDerivative);



			//Scale down to proper motor values
			if( pidElevatorDrive > PID_DRIVE_MAX )
				pidElevatorDrive = PID_DRIVE_MAX;
			if( pidElevatorDrive < PID_DRIVE_MIN )
				pidElevatorDrive = PID_DRIVE_MIN;


			//Drive using PID commands
			motor[elevatorOne] = (int)pidElevatorDrive;


			wait1Msec(CYCLE_TIME);

		}

	}
}

task usercontrol()
{
  while(true)
	{
		motor[driveLeftOne] = vexRT[Ch3] + vexRT[Ch1];
		motor[driveLeftTwo] = vexRT[Ch3] + vexRT[Ch1];
		motor[driveLeftThree] = vexRT[Ch3] + vexRT[Ch1];
		motor[driveLeftFour] = vexRT[Ch3] + vexRT[Ch1];

		motor[driveRightOne] = vexRT[Ch3] - vexRT[Ch1];
		motor[driveRightTwo] = vexRT[Ch3] - vexRT[Ch1];
		motor[driveRightThree] = vexRT[Ch3] - vexRT[Ch1];
		motor[driveRightFour] = vexRT[Ch3] - vexRT[Ch1];

		if(vexRT[Btn6U] == 1)
		{
			motor[liftLeft] = 127;
			motor[liftRight] = 127;
		}
		else
		if(vexRT[Btn6D] == 1)
		{
			motor[liftLeft] = -127;
			motor[liftRight] = -127;
		}
		else
		{
			motor[liftLeft] = 0;
			motor[liftRight] = 0;
		}
	}
}
