#pragma config(Sensor, in1,    autonSelector,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  elevatorEnc,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  chainBarEnc,    sensorQuadEncoder)
#pragma config(Motor,  port1,           mogoLeft,      tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveFrontRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           elevator,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           driveBackRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveBackLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           chainBarLeft,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           chainBarRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          mogoRight,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


//DRIVE CONTROL LOOP
#define PID_INTEGRAL_LIMIT  50
#define PID_DRIVE_MAX       127
#define PID_DRIVE_MIN     (-127)
#define CYCLE_TIME 					20


static float pidRequestedValueLeft, pidRequestedValueRight;
static float Kp = 1;
static float Ki = 0;
static float Kd = 0;
static float leftDriveScale = 1.0; //Multiply faster motor by this so speed is equal with slower motor
static float rightDriveScale = 1.0;
static bool pidActive = true;


static float velErrorKp = .1;

bool matchSideVelocities = true;

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task pidDriveController()
{
	//Initialize PID variables, only using P for now
	float  pidSensorCurrentValueLeft, pidSensorCurrentValueRight;
	float  pidErrorLeft, pidErrorRight;
	float  pidLastErrorLeft, pidLastErrorRight;
	float  pidIntegralLeft, pidIntegralRight;
	float  pidDerivativeLeft, pidDerivativeRight;
	float  pidDriveLeft, pidDriveRight;

	float velDiffError;


	//Clear sensor values
	SensorValue[rightEnc] = 0;
	SensorValue[leftEnc] = 0;

	pidLastErrorLeft = 0;
	pidLastErrorRight = 0;
	pidIntegralLeft = 0;
	pidIntegralRight = 0;

	velDiffError = 0;
	while(true)
	{
		//If the pid is set to active
		if(pidActive)
		{
			//Calculate proportional portion
			pidSensorCurrentValueLeft = SensorValue[leftEnc];
			pidSensorCurrentValueRight = SensorValue[rightEnc];

			pidErrorLeft = pidSensorCurrentValueLeft - pidRequestedValueLeft;
			pidErrorRight = pidSensorCurrentValueRight - pidRequestedValueRight;


			// Calculate integral portion
			// Add the error to the integral unless the error bound grows too large
			if(abs(pidErrorLeft) < PID_INTEGRAL_LIMIT)
				pidIntegralLeft = pidIntegralLeft + pidErrorLeft;
			else
				pidIntegralLeft = 0;

			if(abs(pidErrorRight) < PID_INTEGRAL_LIMIT)
				pidIntegralRight = pidIntegralRight + pidErrorRight;
			else
				pidIntegralRight = 0;

			//Calculate derivitave portion
			pidDerivativeLeft = pidErrorLeft - pidLastErrorLeft;
			pidDerivativeRight = pidErrorRight - pidLastErrorRight;

			pidLastErrorLeft  = pidErrorLeft;
			pidLastErrorRight = pidErrorRight;

			//Compensate for one side moving faster
			velDiffError = pidSensorCurrentValueLeft - pidSensorCurrentValueRight;

			writeDebugStreamLine("LeftEnc: %f", pidSensorCurrentValueLeft);
			writeDebugStreamLine("RightEnc: %f", pidSensorCurrentValueRight);


			//Calculate drive
			pidDriveLeft = (Kp * pidErrorLeft) + (Ki * pidIntegralLeft) + (Kd * pidDerivativeLeft);
			pidDriveRight = (Kp * pidErrorRight) + (Ki * pidIntegralRight) + (Kd * pidDerivativeRight);



			//Scale down to 127, -127 so drive distance gains do not override corrective vel matching
			if( pidDriveLeft > PID_DRIVE_MAX )
				pidDriveLeft = PID_DRIVE_MAX;
			if( pidDriveLeft < PID_DRIVE_MIN )
				pidDriveLeft = PID_DRIVE_MIN;

			if( pidDriveRight > PID_DRIVE_MAX )
				pidDriveRight = PID_DRIVE_MAX;
			if( pidDriveRight < PID_DRIVE_MIN )
				pidDriveRight = PID_DRIVE_MIN;

					writeDebugStreamLine("DriveBeforeCorrectLeft: %f", pidDriveLeft);
				writeDebugStreamLine("DriveBeforeCorrectRight: %f", pidDriveRight);


		  //Recalculate drive with corrective vel matching on each side
			pidDriveLeft = pidDriveLeft + (velErrorKp * velDiffError);
			pidDriveRight = pidDriveRight - (velErrorKp * velDiffError);

			writeDebugStreamLine("Vel Error: %f", velDiffError);

			writeDebugStreamLine("DriveLeft After: %f", pidDriveLeft);
			writeDebugStreamLine("DriveRight After: %f", pidDriveRight);


			//Prevent setting over valid motor values once more
			if( pidDriveLeft > PID_DRIVE_MAX )
				pidDriveLeft = PID_DRIVE_MAX;
			if( pidDriveLeft < PID_DRIVE_MIN )
				pidDriveLeft = PID_DRIVE_MIN;

			if( pidDriveRight > PID_DRIVE_MAX )
				pidDriveRight = PID_DRIVE_MAX;
			if( pidDriveRight < PID_DRIVE_MIN )
				pidDriveRight = PID_DRIVE_MIN;

			writeDebugStreamLine("Final Left : %f", pidDriveLeft);
			writeDebugStreamLine("Final Right : %f", pidDriveRight);


			//Drive using PID commands
			motor[driveFrontLeft] = (int)((float)pidDriveLeft * (-1.0)*leftDriveScale);
			motor[driveBackLeft] = (int)((float)pidDriveLeft * (-1.0)*leftDriveScale);
			motor[driveFrontRight] = (int)((float)pidDriveRight * (-1.0)*rightDriveScale);
			motor[driveBackRight] = (int)((float)pidDriveRight * (-1.0)*rightDriveScale);

			wait1Msec(CYCLE_TIME);
		}
		else //delete the emails, i mean variables
		{
			pidSensorCurrentValueLeft = 0;
			pidSensorCurrentValueRight = 0;
			pidErrorLeft = 0;
			pidErrorRight = 0;
			pidLastErrorLeft = 0;
			pidLastErrorRight = 0;
			pidIntegralLeft = 0;
			pidIntegralRight = 0;
			pidDerivativeLeft = 0;
			pidIntegralRight = 0;
			pidDriveLeft= 0;
			pidDriveRight = 0;
			motor[driveFrontRight] = 0;
			motor[driveFrontLeft] = 0;
			motor[driveBackRight] = 0;
			motor[driveBackLeft] = 0;
		}

	}
}

//LIFT CONTROL LOOP
#define PID_INTEGRAL_LIMIT_ELEVATOR  50
#define PID_INTEGRAL_LIMIT_ARM 50

static float pidRequestedElevator;
static float elevatorKp = 1;
static float elevatorKi = 0;
static float elevatorKd = 0;
static bool pidLift = false;

static float pidRequestedArm;
static float armKp = 1;
static float armKi = 0;
static float armKd = 0;
static bool pidArm = false;

task liftControl()
{
	float  currentElevatorPos;
	float  pidElevatorError;
	float  pidLastElevatorError;
	float  pidElevatorIntegral;
	float  pidElevatorDerivative;
	float  pidElevatorDrive;

	float  currentArmPos;
	float  pidArmError;
	float  pidLastArmError;
	float  pidArmIntegral;
	float  pidArmDerivative;
	float  pidArmDrive;

	while(true)
	{
		if(pidLift)
		{
			currentElevatorPos = SensorValue[elevator];

			pidElevatorError = currentElevatorPos - pidRequestedElevator;

			// Calculate integral portion
			// Add the error to the integral unless the error bound grows too large
			if(abs(pidElevatorError) < PID_INTEGRAL_LIMIT_ELEVATOR)
				pidElevatorIntegral = pidElevatorIntegral + pidElevatorError;
			else
				pidElevatorIntegral = 0;


			//Calculate derivitave portion
			pidElevatorDerivative = pidElevatorError - pidLastElevatorError;

			pidLastElevatorError = pidElevatorError;


			//Calculate drive
			pidElevatorDrive = (elevatorKp * pidElevatorError) + (elevatorKi * pidElevatorIntegral) + (elevatorKd * pidElevatorDerivative);



			//Scale down to proper motor values
			if( pidElevatorDrive > PID_DRIVE_MAX )
				pidElevatorDrive = PID_DRIVE_MAX;
			if( pidElevatorDrive < PID_DRIVE_MIN )
				pidElevatorDrive = PID_DRIVE_MIN;


			//Drive using PID commands
			motor[elevator] = (int)pidElevatorDrive;
		}

		if(pidArm)
		{
			currentArmPos = SensorValue[elevator];

			pidArmError = currentArmPos - pidRequestedArm;

			// Calculate integral portion
			// Add the error to the integral unless the error bound grows too large
			if(abs(pidArmError) < PID_INTEGRAL_LIMIT_ARM)
				pidArmIntegral = pidArmIntegral + pidArmError;
			else
				pidElevatorIntegral = 0;


			//Calculate derivitave portion
			pidArmDerivative = pidArmError - pidLastArmError;

			pidLastArmError = pidArmError;


			//Calculate drive
			pidArmDrive = (armKp * pidArmError) + (armKi * pidArmIntegral) + (armKd * pidArmDerivative);



			//Scale down to proper motor values
			if( pidArmDrive > PID_DRIVE_MAX )
				pidArmDrive = PID_DRIVE_MAX;
			if( pidArmDrive < PID_DRIVE_MIN )
				pidArmDrive = PID_DRIVE_MIN;


			//Drive using PID commands
			motor[chainBarLeft] = (int)pidArmDrive;
			motor[chainBarRight] = (int)pidArmDrive;




		}
		wait1Msec(CYCLE_TIME);

	}
}


void drive(int anglesLeft, int anglesRight)
{
	matchSideVelocities = false;
	SensorValue[leftEnc] = 0;
	SensorValue[rightEnc] = 0;

	pidRequestedValueLeft = anglesLeft;
	pidRequestedValueRight = anglesRight;

}

void driveStraight(int dist)
{
	matchSideVelocities = true;
	SensorValue[leftEnc] = 0;
	SensorValue[rightEnc] = 0;

	pidRequestedValueLeft = dist;
	pidRequestedValueRight = dist;

}
void mogoDown()
{
	motor[mogoLeft] = -127;
	motor[mogoRight] = -127;
	wait1Msec(500);
	motor[mogoLeft] = 0;
	motor[mogoRight] = 0;
}

void mogoUp()
{
	motor[mogoLeft] = 127;
	motor[mogoRight] = 127;
	wait1Msec(800);
	motor[mogoLeft] = 0;
	motor[mogoRight] = 0;
}

void setLift(int cmd_id)
{
	switch(cmd_id)
	{
		case 1:
		{
			break;
		}
		case 2:
		{
			break;
		}
		case 3:
		{
			break;
		}

		default:
	}
}

task autonomous()
{
	/*
if(SensorValue[autonSelector] < 1700)
	{
		//Red
		startTask(pidDriveController);
		drive(1620,1620);
		mogoDown();
		wait1Msec(1350);
		mogoUp();
		wait1Msec(700);
		drive(-800,-800);
		wait1Msec(1000);
		drive(625,-625);
		wait1Msec(1400);
		drive(1450,1050);
		wait1Msec(2200);
		drive(600,600);
		wait1Msec(1000);
		mogoDown();
		wait1Msec(1000);
		drive(-700,-700);
  }
  else
	{
		startTask(pidDriveController);
		drive(1600,1600);
		mogoDown();
		wait1Msec(1350);
		mogoUp();
		wait1Msec(700);
		drive(-800,-800);
		wait1Msec(1000);
		drive(-625,625);
		wait1Msec(1400);
		drive(1050,1450);
		wait1Msec(2200);
		drive(600,600);
		wait1Msec(1000);
		mogoDownStrong();
		wait1Msec(1000);
		drive(-700,-700);
	}*/
		startTask(pidDriveController);
	  driveStraight(8000);
		//drive(1000,1000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task usercontrol()
{
  while(true)
	{
		motor[driveFrontLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[driveBackLeft] = vexRT[Ch3] + vexRT[Ch1];

		motor[driveFrontRight] = vexRT[Ch3] - vexRT[Ch1];
		motor[driveBackRight] = vexRT[Ch3] - vexRT[Ch1];

		if(vexRT[Btn6U] == 1)
		{
			motor[mogoLeft] = 127;
			motor[mogoRight] = 127;
		}
		else
		if(vexRT[Btn6D] == 1)
		{
			motor[mogoLeft] = -127;
			motor[mogoRight] = -127;
		}
		else
		{
			motor[mogoLeft] = 0;
			motor[mogoRight] = 0;
		}
	}
}
